apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - postgres.yaml
  - migration-job.yaml
  - application.yaml
  - monitoring.yaml
  - backup-cronjob.yaml

