apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secrets
  namespace: ecommerce
type: Opaque
stringData:
  POSTGRES_PASSWORD: cambiar-en-terraform
  JWT_SECRET: cambiar-en-terraform
  GRAFANA_ADMIN_PASSWORD: cambiar-en-terraform

